### ISSUE TITLE
Source generator don't work in latest sdk version 7.0.200 (.NET 7.0.3)

### ISSUE THREAD

**Issue by jarlef** [byme8/ZeroQL#28]
**Describe the bug**
Microsoft just launched a security fix yesterday ([.NET 7.0.3](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.3/7.0.3.md?WT.mc_id=dotnet-35129-website))

This breaks the ZeroQL source generator 

```ZeroQL.SourceGenerators/ZeroQL.SourceGenerators.Generator.GraphQLLambdaIncrementalSourceGenerator/ZeroQLModuleInitializer.24cfda3e5e964b5c9dc6bda0646f82b4.g.cs(32,34): Error CS0305: Using the generic type 'GraphQLResult<TData>' requires 1 type arguments```

**How to Reproduce**
Install latest .NET SDK (7.0.200)

**Environment (please complete the following information):**
 - .NET Version [7.0.3] (SDK 7.0.200)

**Comment by byme8** [comment]
I could not reproduce the issue with .NET SDK 7.0.200 and ZeroQL 3.4.1-preview.1 inside VS.

You have skipped the following fields from the template:
```
Environment (please complete the following information):
    Nuget version [3.0.0]
    IDE: [VS, VS for Mac, Rider, VS Code]
```
So, what is your IDE and NuGet version?

**Comment by byme8** [comment]
How does the query on the C# level look? I suppose it can be related.

**Comment by DaveRMaltby** [comment]
I am seeing the same error in my GitHub Actions build for Linux:

`/home/runner/work/MockDB/MockDB/Tests/Integration.ExtendedSchema.ClientCodeGeneration/ZeroQL.SourceGenerators/ZeroQL.SourceGenerators.Generator.GraphQLLambdaIncrementalSourceGenerator/ZeroQLModuleInitializer.8a1de5d71ed041bfa5d18c449c940b84.g.cs(32,34): error CS0305: Using the generic type 'GraphQLResult<TData>' requires 1 type arguments [/home/runner/work/MockDB/MockDB/Tests/Integration.ExtendedSchema.ClientCodeGeneration/MockDB.Integration.ExtendedSchema.ClientCodeGeneration.csproj]
`

On my Windows dev box, I don't get such an error at all.

Microsoft's GitHub build agent -- Current runner version: '2.301.1'
Operating System
  Ubuntu
  22.04.1
  LTS

Originally, I was running ZeroQL 3.3.3 ... but 3.4 has the same issue..
	<PackageReference Update="ZeroQL" Version="3.4.0" />
	<PackageReference Update="ZeroQL.Tools" Version="3.4.0" />

In addition, I also get the error:

`/home/runner/work/MockDB/MockDB/Tests/Integration.ExtendedSchema.ClientCodeGeneration/ZeroQL.SourceGenerators/ZeroQL.SourceGenerators.Generator.GraphQLLambdaIncrementalSourceGenerator/ZeroQLModuleInitializer.8a1de5d71ed041bfa5d18c449c940b84.g.cs(32,100): error CS0246: The type or namespace name 'mutations' could not be found (are you missing a using directive or an assembly reference?) [/home/runner/work/MockDB/MockDB/Tests/Integration.ExtendedSchema.ClientCodeGeneration/MockDB.Integration.ExtendedSchema.ClientCodeGeneration.csproj]
`

It appeared at the same time, but could potentially be related to GraphQL schema changes that I just made.  (Although, I also don't get that error on my Windows dev box.

**Comment by DaveRMaltby** [comment]
@byme8, I'll try a build in GitHub Actions with  

```
jobs:
  build:
    runs-on: windows-latest 
    #runs-on:  ubuntu-latest
```
and let you know in a few minutes...

**Comment by DaveRMaltby** [comment]
I see the same errors on windows-latest:

```
Error: D:\a\MockDB\MockDB\Tests\Integration.ExtendedSchema.ClientCodeGeneration\ZeroQL.SourceGenerators\ZeroQL.SourceGenerators.Generator.GraphQLLambdaIncrementalSourceGenerator\ZeroQLModuleInitializer.c2711003f48d4af69318be105bc76f0c.g.cs(32,34): error CS0305: Using the generic type 'GraphQLResult<TData>' requires 1 type arguments [D:\a\MockDB\MockDB\Tests\Integration.ExtendedSchema.ClientCodeGeneration\MockDB.Integration.ExtendedSchema.ClientCodeGeneration.csproj]
Error: D:\a\MockDB\MockDB\Tests\Integration.ExtendedSchema.ClientCodeGeneration\ZeroQL.SourceGenerators\ZeroQL.SourceGenerators.Generator.GraphQLLambdaIncrementalSourceGenerator\ZeroQLModuleInitializer.c2711003f48d4af69318be105bc76f0c.g.cs(32,100): error CS0246: The type or namespace name 'mutations' could not be found (are you missing a using directive or an assembly reference?) [D:\a\MockDB\MockDB\Tests\Integration.ExtendedSchema.ClientCodeGeneration\MockDB.Integration.ExtendedSchema.ClientCodeGeneration.csproj]

```

**Comment by byme8** [comment]
I managed to reproduce it on MacOS with 7.0.200. I am going to have a look.

**Comment by DaveRMaltby** [comment]
To confirm and verify the workaround... reverting back on the .NET SDK does solve the issues.  Here are the files that I changed...
![image](https://user-images.githubusercontent.com/88258058/219871817-dc98cc58-65ca-4f40-bfda-d28a080386c6.png)
![image](https://user-images.githubusercontent.com/88258058/219871888-ec4b0dd6-5106-4796-95df-fe08c78d62ee.png)

**Comment by byme8** [comment]
Checkout v3.4.1-preview.2.

**Comment by DaveRMaltby** [comment]
@byme8, I have now confirmed that with preview 2 the issue is now fixed.  Thank you!

**Comment by jarlef** [comment]
Will take a look at it. It happend in our azure devops pipeline running ubuntu, not our local dev environment since we havent upgraded our local dev to the latest sdk.
